In [2]:
import numpy as np

In [4]:
def descomposicionQR(A):
    
    n = A.shape[0]
    
    #Se inicializan Q y R con ceros.
    Q = np.zeros( (n,n), dtype=float ) #Q recibira los vectores ortonormales de A
    R = np.zeros( (n,n), dtype=float ) #R recibira los coeficientes de proyeccion 

    for i in range(n):

        v = A[:, i]

        #Se ortogonalizan los vectores de A
        for j in range(i):
            
           
            R[j,i] = np.dot(Q[:,j],v) #Se guardan por encima de la diagonal los coeficientes de proyeccion 
            v = v - R[j, i]*Q[:,j] #Se calcula la proyección 

        R[i,i] = np.linalg.norm(v) #Se guardan en la diagonal las normas de los vectores ortogonales de A
        Q[:,i] = v / R[i,i]  #Se guarda en Q los vectores ortonormales de A

    return Q, R

In [8]:
def metodoQR(A, tol=1e-8, max_iter = 10000):
    n = A.shape[0]

    A_k = A.copy()

    for _ in range(max_iter):
        Q, R = descomposicionQR(A_k) #Se factoriza A como QR

        A_k = np.dot(R,Q) #Se reescribe A como RQ
        if np.sum(np.abs(A_k - np.diag(np.diagonal(A_k)))) < tol:
            print("Si cumplio error.")
            return np.diagonal(A_k) #Si los elementos por encima de la diagonal son lo suficientemente pequeños que retorne la diagonal
        
    return np.diagonal(A_k)

In [ ]:
#Valores propios esperados [1,5]
A = np.array( [ [2,1], [3,4]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[5. 1.]


In [ ]:
#Valores propios esperados [6,1]
A = np.array( [ [3,2], [3,4]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[6. 1.]


In [ ]:
#Valores propios esperados [5,1]
A = np.array( [ [2,3], [1,4]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[5. 1.]


In [ ]:
#Valores propios esperados ~[4.507, 0.778, -0.285]
A = np.array( [ [1,1,2], [2,1,1], [1,1,3]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[ 4.50701864  0.77812384 -0.28514248]


In [ ]:
#Valores propios esperados ~[4.049,-0.357, -0.692]
A = np.array( [ [1,1,2], [2,1,3], [1,1,1]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[ 4.04891734 -0.69202147 -0.35689587]


In [ ]:
#Valores propios esperados ~[4.403, 0.316, -0.719]
A = np.array( [ [2,1,2], [2,1,3], [1,1,1]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[ 4.40267883 -0.71870969  0.31603086]


In [ ]:
#Valores propios esperados ~[-0.736, -0.407, 1.509, 6.635]
A = np.array( [ [1,1,1,2], [2,1,1,1], [3,2,1,2], [2,1,1,4]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[ 6.63453446  1.50856334 -0.73564154 -0.40745627]


In [ ]:
#Valores propios esperados ~[-1.088, -0.467, 1.728, 6.827]
A = np.array( [ [1,2,1,2], [2,1,1,1], [3,2,1,2], [2,1,1,4]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[ 6.82726225  1.72811591 -1.08793492 -0.46744323]
